## https://docs.aws.amazon.com/lambda/latest/dg//build-pipeline.html
version: 0.2
phases:
    install:
        runtime-versions:
            nodejs: 10
    build:
        commands:
            - npm install time
            - export BUCKET=lambda-deployment-artifacts-630778274080
            - export PREFIX=codebuild
            - aws cloudformation package --template-file template.yml --s3-bucket $BUCKET --s3--prefix $PREFIX --output-template-file outputtemplate.yml
artifacts:
    type: zip
    files:
        - template.yml
        - outputtemplate.yml
