## https://docs.aws.amazon.com/lambda/latest/dg//build-pipeline.html
version: 0.2
phases:
    install:
        runtime-versions:
            nodejs: 10
    build:
        commands:
            - echo "$CODEBUILD_WEBHOOK_BASE_REF"
            - npm install --prefix ./aws/lambda time
            - export BUCKET="lab666-scott-codepipeline"
            - export S3_PREFIX="dev-sagemaker/CfnPackage"
            - >
                aws cloudformation package --template-file template.yml \
                    --s3-bucket $BUCKET --s3-prefix $S3_PREFIX --kms-key-id $CODEBUILD_KMS_KEY_ID \
                    --output-template-file outputtemplate.yml
artifacts:
    type: zip
    files:
        - template.yml
        - outputtemplate.yml
