Parameters:
  BranchName:
    Description: GitHub branch name
    Type: String
    Default: master
  RepositoryName:
    Description: GitHub repository name
    Type: String
    Default: codepipeline-github
  GitHubOwner:
    Type: String
    Default: HsiehShuJeng
  GitHubOAuthToken:
    Type: String
    Default: "{{resolve:secretsmanager:github/access_token:SecretString:GitHubSecret}}"
  ComputeType:
    AllowedValues:
      - BUILD_GENERAL1_SMALL
      - BUILD_GENERAL1_MEDIUM
      - BUILD_GENERAL1_LARGE
    Default: BUILD_GENERAL1_SMALL
    Description: AWS CodeBuild project compute type.
    Type: String
  ApplicationName:
    Description: CodeDeploy application name
    Type: String
    Default: DemoApplication
  CodePipelineName:
    Description: The name of CodePipeline
    Type: String
    Default: "dev-sagemaker"
  CodePipelineAPPrefix:
    Description: directory for AP on AWS S3
    Type: String
    Default: 'DevSource'
  CodeBuildAPPrefix:
    Description: CodeBuild directory for AP on AWS s3
    Type: String
    Default: 'DevCodeBuild'
  CfnApStack:
    Description: Lambda cfn stack
    Type: String
    Default: 'dev-314159-sagemaker'
  RepositoryLocation:
    AllowedPattern: '^https?://.*$'
    ConstraintDescription: 'RepositoryLocation must be the HTTPS clone URL to the repository.'
    Description: 'The repository location, e.g., https://github.com/example/example.git'
    Type: String
    Default: 'https://github.com/HsiehShuJeng/codepipeline-github.git'
  RepositoryType:
    AllowedValues: 
      - 'GITHUB'
    ConstraintDescription: "RepositoryType must be a valid repository type. Allowed values: GITUHB"
    Description: "The repository type, e.g. GITHUB"
    Type: String
    Default: 'GITHUB'
  ProjectName:
    Description: CodeBuild project name
    Type: String
    Default: dev-sagemaker
  BetaFleet:
    Description: Fleet configured in CodeDeploy
    Type: String
    Default: DemoFleet
Resources:
  # S3 bucket for build artifacts from CodePipeLine
  CodePipelineArtifactStoreBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: 'devscott-codepipeline'
  CodePipelineArtifactStoreBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref CodePipelineArtifactStoreBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: DenyUnEncryptedObjectUploads
            Effect: Deny
            Principal: '*'
            Action: 's3:PutObject'
            Resource: !Join 
              - ''
              - - !GetAtt CodePipelineArtifactStoreBucket.Arn
                - /*
            Condition:
              StringNotEquals:
                's3:x-amz-server-side-encryption': 'aws:kms'
          - Sid: DenyInsecureConnections
            Effect: Deny
            Principal: '*'
            Action: 's3:*'
            Resource: !Join 
              - ''
              - - !GetAtt CodePipelineArtifactStoreBucket.Arn
                - /*
            Condition:
              Bool:
                'aws:SecureTransport': false
  AppCodeBuild:
    DependsOn:
      - "CodeBuildServiceRole"
    Type: "AWS::CodeBuild::Project"
    Metadata:
      Comment: "https://docs.aws.amazon.com/codebuild/latest/userguide/sample-github-pull-request.html#sample-github-pull-request-filter-webhook-events-cfn"
    Properties:
      Name: !Ref ProjectName
      ServiceRole: !Ref CodeBuildServiceRole
      # specifies output settings for artifacts generated by an AWS CodeBild build
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: !Ref ComputeType
        Image: aws/codebuild/standard:2.0
      Source:
        Type: CODEPIPELINE
      # Triggers:
      #   Webhook: true
      #   FilterGroups:
      #     - - Type: EVENT
      #         Pattern: PUSH
      #       - Type: BASE_REF
      #         Pattern: ^refs/heads/master$
      #         ExcludeMatchedPattern: false
      #       - Type: HEAD_REF
      #         Pattern: ^refs/tags/v[0-9]*
      #       - Type: ACTOR_ACCOUNT_ID
      #         Pattern: HsiehShuJeng
      #         ExcludeMatchedPattern: true

  ApPipelineWebhook:
    Type: 'AWS::CodePipeline::Webhook'
    Properties:
      Authentication: GITHUB_HMAC
      AuthenticationConfiguration:
        SecretToken: !Ref GitHubOAuthToken
      Filters:
        - JsonPath: $.ref
          MatchEquals: !Sub 'refs/heads/${BranchName}'
      TargetPipeline: !Ref ApPipeline
      TargetAction: SourceAction
      Name: ApPipelineWebhook
      TargetPipelineVersion: !GetAtt ApPipeline.Version
      RegisterWithThirdParty: true

  ApPipeline:
    DependsOn:
      - "CodePipelineServiceRole"
    Type: 'AWS::CodePipeline::Pipeline'
    Properties:
      Name: !Sub "${CodePipelineName}"
      RoleArn: !GetAtt CodePipelineServiceRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref CodePipelineArtifactStoreBucket
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: 1
                Provider: GitHub
              Configuration:
                Owner: !Ref GitHubOwner
                Repo: !Ref RepositoryName
                Branch: !Ref BranchName
                OAuthToken: !Ref GitHubOAuthToken
                PollForSourceChanges: false
              OutputArtifacts:
                - Name: !Sub "${CodePipelineAPPrefix}"
              RunOrder: 1
              Namespace: SourceVariables
        - Name: BuildResources
          Actions:
            - Name: GitTagDetect
              InputArtifacts:
                - Name: !Sub "${CodePipelineAPPrefix}"
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              Configuration:
                EnvironmentVariables: "[{\"name\":\"Release_ID\",\"value\":\"#{codepipeline.PipelineExecutionId}\",\"type\":\"PLAINTEXT\"},{\"name\":\"Commit_ID\",\"value\":\"#{SourceVariables.CommitId}\",\"type\":\"PLAINTEXT\"}]"
                ProjectName: !Ref ProjectName
              OutputArtifacts:
                - Name: !Sub "${CodeBuildAPPrefix}"
              RunOrder: 1
        - Name: Deploy
          Actions:
            - Name: ChangeSet
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              InputArtifacts:
                - Name: !Sub "${CodeBuildAPPrefix}"
              Configuration:
                ActionMode: CHANGE_SET_REPLACE
                Capabilities: CAPABILITY_IAM
                ChangeSetName: 'dev-314159-changeset'
                RoleArn: !GetAtt CodePipelineServiceRole.Arn
                StackName: !Sub "${CfnApStack}"
                TemplatePath: !Join ['', [!Sub '${CodeBuildAPPrefix}', '::outputtemplate.yml']]
              RunOrder: 1
            - Name: ExecuteChangeSet
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              InputArtifacts:
                - Name: !Sub "${CodeBuildAPPrefix}"
              Configuration:
                ActionMode: CHANGE_SET_EXECUTE
                ChangeSetName: 'dev-314159-changeset'
                StackName: !Sub "${CfnApStack}"
              RunOrder: 2
  CodePipelineServiceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
                - cloudformation.amazonaws.com
            Action: 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: 'dev01-start-execution-codepipeline-testapp'
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'codedeploy:CreateDeployment'
                  - 'codedeploy:GetApplicationRevision'
                  - 'codedeploy:GetDeployment'
                  - 'codedeploy:GetDeploymentConfig'
                  - 'codedeploy:RegisterApplicationRevision'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 'codebuild:BatchGetBuilds'
                  - 'codebuild:StartBuild'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 'lambda:AddPermission'
                  - 'lambda:RemovePermission'
                  - 'lambda:InvokeFunction'
                  - 'lambda:GetFunction'
                  - 'lambda:ListFunctions'
                  - 'lambda:CreateFunction'
                  - 'lambda:DeleteFunction'
                  - 'lambda:GetFunctionConfiguration'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 'iam:PassRole'
                  - 'iam:GetRole'
                  - 'iam:CreateRole'
                  - 'iam:AttachRolePolicy'
                  - 'iam:DetachRolePolicy'
                  - 'iam:DeleteRole'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 'ec2:*'
                  - 'elasticloadbalancing:*'
                  - 'autoscaling:*'
                  - 'cloudwatch:*'
                  - 's3:*'
                  - 'sns:*'
                  - 'cloudformation:*'
                  - 'rds:*'
                  - 'sqs:*'
                  - 'ecs:*'
                  - 'apigateway:*'
                Resource: '*'
  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      # the purpose of Path?
      Path: /
      Description: !Sub "Used in CodeBuild project. Created by CloudFormation ${AWS::StackId}"
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
      Policies:
        - PolicyName: !Sub 'DevCodebuild${ApplicationName}'
          PolicyDocument:
            Version: 2012-10-17
            Statement:
            - Effect: Allow
              Action:
                - 'logs:CreateLogGroup'
                - 'logs:CreateLogStream'
                - 'logs:PutLogEvents'
              Resource:
                - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/*'
            - Effect: Allow
              Action:
                - 's3:GetObject'
                - 's3:GetObjectVersion'
                - 's3:PutObject'
                - 's3:PutObjectAcl'
              Resource:
                - !Join ['', ['arn:aws:s3:::', !Ref CodePipelineArtifactStoreBucket, '/*']]
Outputs:
  ApPipelineName:
    Description: The name of the CodePipeline
    Value: !Ref ApPipeline
  ApPipelineArtifactStore:
    Description: The ARN of the CodePipeline
    Value: !Join ['', [!Sub 'arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:', !Ref ApPipeline]]
  CodePipelineArtifactStoreBucket:
    Description: S3 bucket where artificats are placed
    Value: !Ref CodePipelineArtifactStoreBucket
  CodePipelineAPPrefix:
    Description: The name of input artifact
    Value: !Sub "${CodePipelineAPPrefix}"
  CodeBuildAPPrefix:
    Description: The name of artifact name for CodeBuild
    Value: !Sub "${CodeBuildAPPrefix}"